spring:
  application:
    name: uaa
  datasource:
    url: jdbc:mariadb://localhost:3306/uaa
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: uaa-${random.int[1,1000]}

server:
  port: 9999
  error:
    include-stacktrace=never: never

# Custom properties
jwt:
  jwtExpirationMs: 3600000
  refreshTokenExpirationMs: 604800000
  jwtSecret: ltlqdqefqewfqfqwqqwdqwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq